---
title: "R_6장_연습문제"
author: "PYB"
date: '2020 12 30 '
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 조건에 맞는 데이터만 추출하기

### **filter()** 함수 이용

#### 1. 패키지 로드 및 파일 불러오기
```{r}
library(dplyr)
exam <- read.csv("csv_exam.csv")
exam
```

(1) 단일 조건 적용(같다, 다르다, 이상, 초과, 이하, 미만)
```{r}
exam %>% filter(class == 1) # exam에서 class가 1인 경우만 추출해 출력
exam %>%  filter(class != 1) # 1반이 아닌 경우
exam %>%  filter(math > 50) # 수학 점수가 50점을 초과한 경우
exam %>%  filter(math < 50) # 수학 점수가 50점 미만인 경우
exam %>% filter(english >= 80) # 영어 점수가 80점 이상인 경우
```

(2) 여러 조건 적용(그리고, 또는)
```{r}
# 1반이면서 수학 점수가 50점 이상인 경우
exam  %>%  filter(class == 1 & math >= 50)

# 2반이면서 영어 점수가 80점 이상인 경우
exam %>% filter(class == 2 & english >= 80)

# 영어 점수가 90점 미만이거나 과학 점수가 50점 미만인 경우
exam %>%  filter(english < 90 | science < 50)

# 1, 3, 5반에 해당하면 추출
exam %>%  filter(class == 1 | class == 3 | class == 5)

exam %>% filter(class %in% c(1, 3, 5)) # 1, 3, 5반에 해당하면 추출
```

(3) 추출한 행으로 데이터 만들기
```{r}
class1 <- exam %>%  filter(class == 1) # class가 1인 행 추출, class1에 할당
class2 <- exam %>%  filter(class == 2) # class가 2인 행 추출, class2에 할당
mean(class1$math) # 1반의 수학 점수 평균
mean(class2$math) # 2반의 수학 점수 평균
```


